// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: pres.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pres struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id  uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Pres) Reset() {
	*x = Pres{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pres_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pres) ProtoMessage() {}

func (x *Pres) ProtoReflect() protoreflect.Message {
	mi := &file_pres_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pres.ProtoReflect.Descriptor instead.
func (*Pres) Descriptor() ([]byte, []int) {
	return file_pres_proto_rawDescGZIP(), []int{0}
}

func (x *Pres) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Pres) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Slide struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageWidth  uint32 `protobuf:"varint,2,opt,name=image_width,json=imageWidth,proto3" json:"image_width,omitempty"`
	ImageHeight uint32 `protobuf:"varint,3,opt,name=image_height,json=imageHeight,proto3" json:"image_height,omitempty"`
	Idx         uint32 `protobuf:"varint,4,opt,name=idx,proto3" json:"idx,omitempty"`
}

func (x *Slide) Reset() {
	*x = Slide{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pres_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slide) ProtoMessage() {}

func (x *Slide) ProtoReflect() protoreflect.Message {
	mi := &file_pres_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slide.ProtoReflect.Descriptor instead.
func (*Slide) Descriptor() ([]byte, []int) {
	return file_pres_proto_rawDescGZIP(), []int{1}
}

func (x *Slide) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Slide) GetImageWidth() uint32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *Slide) GetImageHeight() uint32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

func (x *Slide) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type Slides struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Slide []*Slide `protobuf:"bytes,2,rep,name=slide,proto3" json:"slide,omitempty"`
	Num   uint32   `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *Slides) Reset() {
	*x = Slides{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pres_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slides) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slides) ProtoMessage() {}

func (x *Slides) ProtoReflect() protoreflect.Message {
	mi := &file_pres_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slides.ProtoReflect.Descriptor instead.
func (*Slides) Descriptor() ([]byte, []int) {
	return file_pres_proto_rawDescGZIP(), []int{2}
}

func (x *Slides) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Slides) GetSlide() []*Slide {
	if x != nil {
		return x.Slide
	}
	return nil
}

func (x *Slides) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_pres_proto protoreflect.FileDescriptor

var file_pres_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x72,
	0x65, 0x73, 0x22, 0x28, 0x0a, 0x04, 0x50, 0x72, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x05,
	0x53, 0x6c, 0x69, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x64, 0x78, 0x22,
	0x4f, 0x0a, 0x06, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x05, 0x73,
	0x6c, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x65,
	0x73, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x52, 0x05, 0x73, 0x6c, 0x69, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x32, 0x2c, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x05, 0x53,
	0x70, 0x6c, 0x69, 0x74, 0x12, 0x0a, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x73,
	0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x2e, 0x53, 0x6c, 0x69, 0x64, 0x65, 0x73, 0x42, 0x23,
	0x5a, 0x21, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pres_proto_rawDescOnce sync.Once
	file_pres_proto_rawDescData = file_pres_proto_rawDesc
)

func file_pres_proto_rawDescGZIP() []byte {
	file_pres_proto_rawDescOnce.Do(func() {
		file_pres_proto_rawDescData = protoimpl.X.CompressGZIP(file_pres_proto_rawDescData)
	})
	return file_pres_proto_rawDescData
}

var file_pres_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pres_proto_goTypes = []interface{}{
	(*Pres)(nil),   // 0: pres.Pres
	(*Slide)(nil),  // 1: pres.Slide
	(*Slides)(nil), // 2: pres.Slides
}
var file_pres_proto_depIdxs = []int32{
	1, // 0: pres.Slides.slide:type_name -> pres.Slide
	0, // 1: pres.Parsing.Split:input_type -> pres.Pres
	2, // 2: pres.Parsing.Split:output_type -> pres.Slides
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pres_proto_init() }
func file_pres_proto_init() {
	if File_pres_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pres_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pres); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pres_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slide); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pres_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slides); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pres_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pres_proto_goTypes,
		DependencyIndexes: file_pres_proto_depIdxs,
		MessageInfos:      file_pres_proto_msgTypes,
	}.Build()
	File_pres_proto = out.File
	file_pres_proto_rawDesc = nil
	file_pres_proto_goTypes = nil
	file_pres_proto_depIdxs = nil
}
