// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: pres.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ParsingClient is the client API for Parsing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParsingClient interface {
	Split(ctx context.Context, in *Pres, opts ...grpc.CallOption) (*Slides, error)
}

type parsingClient struct {
	cc grpc.ClientConnInterface
}

func NewParsingClient(cc grpc.ClientConnInterface) ParsingClient {
	return &parsingClient{cc}
}

func (c *parsingClient) Split(ctx context.Context, in *Pres, opts ...grpc.CallOption) (*Slides, error) {
	out := new(Slides)
	err := c.cc.Invoke(ctx, "/pres.Parsing/Split", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParsingServer is the server API for Parsing service.
// All implementations must embed UnimplementedParsingServer
// for forward compatibility
type ParsingServer interface {
	Split(context.Context, *Pres) (*Slides, error)
	mustEmbedUnimplementedParsingServer()
}

// UnimplementedParsingServer must be embedded to have forward compatible implementations.
type UnimplementedParsingServer struct {
}

func (UnimplementedParsingServer) Split(context.Context, *Pres) (*Slides, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Split not implemented")
}
func (UnimplementedParsingServer) mustEmbedUnimplementedParsingServer() {}

// UnsafeParsingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParsingServer will
// result in compilation errors.
type UnsafeParsingServer interface {
	mustEmbedUnimplementedParsingServer()
}

func RegisterParsingServer(s grpc.ServiceRegistrar, srv ParsingServer) {
	s.RegisterService(&Parsing_ServiceDesc, srv)
}

func _Parsing_Split_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pres)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParsingServer).Split(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pres.Parsing/Split",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParsingServer).Split(ctx, req.(*Pres))
	}
	return interceptor(ctx, in, info, handler)
}

// Parsing_ServiceDesc is the grpc.ServiceDesc for Parsing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Parsing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pres.Parsing",
	HandlerType: (*ParsingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Split",
			Handler:    _Parsing_Split_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pres.proto",
}
